<?php

global $metsis_conf;
define('DEBUG', FALSE);
define('DRUPAL_SITE_NAME', $metsis_conf['drupal_site_name']);
define('CAPDOC_POSTFIX', $metsis_conf['capdoc_postfix']);
define('MISSING_METADATA', $metsis_conf['missing_metadata']);
define('NOT_APPLICABLE_METADATA', $metsis_conf['not_applicable_metadata']);
define('MISSING_OPENDAP', $metsis_conf['missing_opendap']);
define('MISSING_DATA_ACCESS_RESOURCE', $metsis_conf['missing_data_access_resource']);
