<?php

require_once drupal_get_path('module', 'metsis_qsearch') . '/metsis_qsearch.constants.inc';
//require_once drupal_get_path('module', 'metsis_qsearch') . '/metsis_qsearch.forms.inc';
//require_once drupal_get_path('module', 'metsis_qsearch') . '/metsis_qsearch.results.inc';
require_once drupal_get_path('module', 'metsis_qsearch') . '/metsis_qsearch.utils.inc';
require_once drupal_get_path('module', 'metsis_qsearch') . '/metsis_qsearch.misc.inc';
require_once drupal_get_path('module', 'metsis_lib') . '/includes/metsis_lib.constants.inc';


use Drupal\Core\Form\FormStateInterface;
function metsis_qsearch_page_attachments(array &$page) {

  //  $page['#attached']['library'][] = 'metsis_wms/style';


//  $page['#attached']['library'][] = 'metsis_lib/tables';

//  $page['#attached']['library'][] = 'metsis_lib/metsis_lib';

//  $page['#attached']['library'][] = 'metsis_lib/icons';

//  $page['#attached']['library'][] = 'metsis_lib/adc_buttons';

//  $page['#attached']['library'][] = 'metsis_lib/autocomplete';

//  $page['#attached']['library'][] = 'metsis_lib/map_thumbnails';

//  $page['#attached']['library'][] = 'metsis_lib/popups';


//  $page['#attached']['library'][] = 'metsis_qsearch/qstyles';


//  $page['#attached']['library'][] = 'metsis_qsearch/qsearch.misc';


//  $page['#attached']['library'][] = 'metsis_lib/qsearch';


//  $page['#attached']['library'][] = 'metsis_lib/utils';


  //$page['#attached']['library'][] = 'metsis_wms/bundle';

}

function metsis_qsearch_theme() {
/*  $module_path = drupal_get_path('module', 'metsis_qsearch');
  return array(
    'metsis_qsearch_form' => array('render element' => 'form'),
    'metadata' => array(
      'variables' => array('content' => NULL),
      'template' => 'metadata',
      'path' => $module_path . '/theme'),
    'wms' => array(
      'variables' => array('content' => NULL),
      'template' => 'wms',
      'path' => $module_path . '/theme'),
    'metadata_inline' => array(
      'variables' => array('content' => NULL),
      'template' => 'metadata_inline',
      'path' => $module_path . '/theme'),
  );*/

/* Add custom twig template to search_form */
  return [
    'metsis_qsearch_form' => [
      'template' => 'metsis-qsearch-form',
      'render element' => 'form',
      //'base hook' => 'form'
    ],
  ];
}

function metsis_qsearch_help($path, $arg) {
  switch ($path) {
    case 'admin/help#metsis_qsearch': $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The METSIS Q search module provides a browser interface to search METADATA indexed in SOLR. Enable this module to provide the "metsis_qsearch" block. Then go to the <a href
="@metsis_qsearch">blocks admin page</a>', array('@metsis_qsearch' => '/metadata_qsearch#overlay=admin/structure/block')) . ' to activate METSIS Q search.</p>';
      return $output;
    case 'admin/content/metsis_qsearch': return '<p>' . t('METSIS Q search.') . '</p>';
  }
}


/** hook_menu is deprecated.
 * TODO: Add needed links and routes defined here to
 * metsis_qsearch.links.menu.yml and metsis_qsearch.routes.eio_symlink
 */

 /*
function metsis_qsearch_menu() {
  $items[METADATA_PREFIX . 'keywords/autocomplete'] = array('title' => 'Autocomplete for mmd_keywords', 'page callback' => 'msb_mmd_keywords_autocomplete', 'access arguments' => array('access content'), 'type' => MENU_CALLBACK);
  $items['metsis/map/wms'] = array('title' => 'METSIS OL3 WMS', 'page callback' => 'metsis_map_wms', 'access arguments' => array('access content'), 'type' => MENU_CALLBACK);
  $items['metsis/map/getcap'] = array('title' => 'GetCapabilities', 'page callback' => 'getCapDoc', 'access arguments' => array('access content'), 'type' => MENU_CALLBACK,);
  $items['metsis/display/metadata'] = array(
  'title' => '',
  'page callback' => 'adc_get_metadata',
  'access arguments' => array('access content'),
  'type' => MENU_CALLBACK,);
  $items['metsis/display/children'] = array('title' => 'Child datasets', 'description' => 'This page is accessible to authenticated users only', 'page callback' => 'drupal_get_form', 'page arguments' => array('msb_display_children_form'), 'access arguments' => array('access content'), 'access callback' => TRUE,);
  $items['authenticated_users_only'] = array('title' => 'Authenticated users', 'page callback' => 'authenticated_users_page_callback_function', 'description' => 'This page is accessible to authenticated users only', 'access arguments' => array('user_is_logged_in'), 'type' => MENU_CALLBACK,);
  $items['results'] = array('title' => 'Search results', 'page callback' => 'qsearch_results_page', 'access callback' => TRUE,);
  return $items;
}
*/
/*
function metsis_qsearch_block_info() {
  $blocks['metsis_qsearch'] = array('info' => t('metsis_qsearch'), 'cache' => DRUPAL_NO_CACHE,);
  return $blocks;
}

function metsis_qsearch_block_view($block_name = '') {
  $block = array();
  switch ($block_name) {
    case 'metsis_qsearch': $metsis_qsearch_block = \Drupal::formBuilder()->getForm('metsis_qsearch_form');
      $block['content'] = \Drupal::service("renderer")->render($metsis_qsearch_block);
      break;
  } return $block;
}
*/

/**
 * Hook to update autocomplete list
 */
function metsis_qsearch_form_metsis_qsearch_form_alter($form, FormStateInterface $form_state, $form_id) {
  global $metsis_conf;
  \Drupal::logger('metsis_qsearch')->debug('Entering metsis_qsearch_form HOOK');
  msb_update_local_mmd_keywords();
  if ($form_state->getValue('rebuild')) {
    $form_state->setValue('input', []);
  }
  //return metsis_qsearch_zero_form($form, $form_state);
}
