<?php

/**
 * @file
 * Export netcdf subset as csv or netcf.
 */

/**
 * Implements hook_help().
 */
function metsis_csv_bokeh_help($path, $arg) {
  switch ($path) {
    case 'help.page.metsis_csv_bokeh':
      $output = '<h3>About</h3>';
      $output .= '<p>This METSIS module provides blocks for configuring and downloading
        time series data as ASCII CSV using the METSIS web services.
        Configure the block from <a href="/metsis_csv_bokeh#overlay=admin/structure/block">blocks admin page</a> to activate and configure METSIS CSV Bokeh.</p>';
      return $output;

    case 'admin/content/metsis_csv_bokeh':
      return '<p>METSIS CSV Bokeh</p>';
  }
}
