<?php

/**
 * Implements hook_help()
 *
 * @param $path
 * @param $arg
 *
 * @return string
 */
function metsis_csv_bokeh_help($path, $arg) {
  switch ($path) {
    case 'help.page.metsis_csv_bokeh':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This METSIS module provides blocks for configuring and downloading
                            time series data as ASCII CSV using the METSIS web services.
                            Configure the block from
                <a href="@metsis_csv_bokeh">blocks admin page</a>', [
          '@metsis_csv_bokeh' => '/metsis_csv_bokeh#overlay=admin/structure/block',
        ]) . ' to activate and configure METSIS CSV Bokeh.</p>';
      return $output;
    case 'admin/content/metsis_csv_bokeh':
      return '<p>' . t('METSIS CSV Bokeh.') . '</p>';
  }
}

