<?php

require_once drupal_get_path('module', 'metsis_qsearch') . '/metsis_qsearch.constants.inc';
require_once drupal_get_path('module', 'metsis_qsearch') . '/metsis_qsearch.forms.inc';
require_once drupal_get_path('module', 'metsis_qsearch') . '/metsis_qsearch.results.inc';
require_once drupal_get_path('module', 'metsis_qsearch') . '/metsis_qsearch.utils.inc';
require_once drupal_get_path('module', 'metsis_qsearch') . '/metsis_qsearch.misc.inc';
require_once drupal_get_path('module', 'metsis_lib') . '/includes/metsis_lib.constants.inc';

function metsis_qsearch_init() {
  drupal_add_css(drupal_get_path('module', 'metsis_wms') . '/css/style.min.css');
  drupal_add_css(drupal_get_path('module', 'metsis_lib') . '/css/tables.css');
  drupal_add_css(drupal_get_path('module', 'metsis_lib') . '/css/metsis_lib.css');
  drupal_add_css(drupal_get_path('module', 'metsis_lib') . '/css/icons.css');
  drupal_add_css(drupal_get_path('module', 'metsis_lib') . '/css/adc-buttons.css');
  drupal_add_css(drupal_get_path('module', 'metsis_lib') . '/css/autocomplete.css');
  drupal_add_css(drupal_get_path('module', 'metsis_lib') . '/css/map_thumbnails.css');
  drupal_add_css(drupal_get_path('module', 'metsis_lib') . '/css/popups.css');
  drupal_add_css(drupal_get_path('module', 'metsis_qsearch') . '/css/qstyles.css');
  drupal_add_css(drupal_get_path('module', 'metsis_qsearch') . '/css/metsis_qsearch_misc.css');
  drupal_add_js(drupal_get_path('module', 'metsis_qsearch') . '/js/metsis_qsearch.js');
  drupal_add_js(drupal_get_path('module', 'metsis_wms') . '/js/bundle.js');
  drupal_add_js(drupal_get_path('module', 'metsis_lib') . '/js/custom/utils.js');
  drupal_add_js(drupal_get_path('module', 'metsis_lib') . '/js/custom/metsis_utils.js');
}

function metsis_qsearch_theme($existing, $type, $theme, $path) {
  $module_path = drupal_get_path('module', 'metsis_qsearch');
  return array('metsis_qsearch_form' => array('render element' => 'form'), 'metadata' => array('variables' => array('content' => NULL), 'template' => 'metadata', 'path' => $module_path . '/theme'), 'wms' => array('variables' => array('content' => NULL), 'template' => 'wms', 'path' => $module_path . '/theme'));
}

function metsis_qsearch_help($path, $arg) {
  switch ($path) {
    case 'admin/help#metsis_qsearch': $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The METSIS Q search module provides a browser interface to search METADATA indexed in SOLR. Enable this module to provide the "metsis_qsearch" block. Then go to the <a href
="@metsis_qsearch">blocks admin page</a>', array('@metsis_qsearch' => '/metadata_qsearch#overlay=admin/structure/block')) . ' to activate METSIS Q search.</p>';
      return $output;
    case 'admin/content/metsis_qsearch': return '<p>' . t('METSIS Q search.') . '</p>';
  }
}

function metsis_qsearch_menu() {
  $items[METADATA_PREFIX . 'keywords/autocomplete'] = array('title' => 'Autocomplete for mmd_keywords', 'page callback' => 'msb_mmd_keywords_autocomplete', 'access arguments' => array('access content'), 'type' => MENU_CALLBACK);
  $items['metsis/map/wms'] = array('title' => 'METSIS OL3 WMS', 'page callback' => 'metsis_map_wms', 'access arguments' => array('access content'), 'type' => MENU_CALLBACK);
  $items['metsis/map/getcap'] = array('title' => 'GetCapabilities', 'page callback' => 'getCapDoc', 'access arguments' => array('access content'), 'type' => MENU_CALLBACK,);
  $items['metsis/display/metadata'] = array('title' => '', 'page callback' => 'adc_get_metadata', 'access arguments' => array('access content'), 'type' => MENU_CALLBACK,);
  $items['metsis/display/children'] = array('title' => 'Child datasets', 'description' => 'This page is accessible to authenticated users only', 'page callback' => 'drupal_get_form', 'page arguments' => array('msb_display_children_form'), 'access arguments' => array('access content'), 'access callback' => TRUE,);
  $items['authenticated_users_only'] = array('title' => 'Authenticated users', 'page callback' => 'authenticated_users_page_callback_function', 'description' => 'This page is accessible to authenticated users only', 'access arguments' => array('user_is_logged_in'), 'type' => MENU_CALLBACK,);
  $items['results'] = array('title' => 'Search results', 'page callback' => 'qsearch_results_page', 'access callback' => TRUE,);
  return $items;
}

function metsis_qsearch_block_info() {
  $blocks['metsis_qsearch'] = array('info' => t('metsis_qsearch'), 'cache' => DRUPAL_NO_CACHE,);
  return $blocks;
}

function metsis_qsearch_block_view($block_name = '') {
  $block = array();
  switch ($block_name) {
    case 'metsis_qsearch': $metsis_qsearch_block = drupal_get_form('metsis_qsearch_form');
      $block['content'] = drupal_render($metsis_qsearch_block);
      break;
  } return $block;
}

function metsis_qsearch_form($form, &$form_state) {
  global $metsis_conf;
  msb_update_local_mmd_keywords();
  if ($form_state['rebuild']) {
    $form_state['input'] = array();
  } return metsis_qsearch_zero_form($form, $form_state);
}
