<?php

function metsis_dashboard_bokeh_help($path, $arg)
{
    switch ($path) {
    case "help.page.metsis_dashboard_bokeh":
      return t("Module for bokeh dashboard");
      break;
  }
}

/**
 * Implements hook_theme() to add the template definition.
 **/
function metsis_dashboard_bokeh_theme($existing, $type, $theme, $path)
{/*
    return [
        'page__metsis__mybasket' => [
          'theme hook' => 'page',
          ],
    ];*/
}
