<?php

/*
 * *******************************************************************
 *                                                                   *
 * DO NOT EDIT this file unless you are comfortable with             *
 * the inner workings of Drupal and the METSIS modules.              *
 * Mistakes in this file WILL BREAK YOUR SITE.                       *
 *                                                                   *
 * *******************************************************************
 */
/**
 * Most of the settings in this file are reasonable defaults and you should
 * not need to change them. You will have to set all the variables that store
 * IP addresses, domain names, service URIs etc.
 * See the METSIS documentation for details of what you need to do as administrator
 * using the Drupal browser interface.
 *
 * It is recommended that you use this files as a starting point, set the
 * variables essential for the site to function (connections to back office services)
 * and then proceed to change the "look and feel" of you site.
 *
 * This file is based on the setting for two production sites at
 * The Norwegian Meteorological Institute:
 *
 * https://satellittdata.no/
 * https://sios-svalbard.org/
 *
 */
/**
 *
 * METSIS global/shared settings for all sites in a multisite environment.
 *"metsis-global-settings.php" is only used if you are running Drupal multisite and
 * want to keep custom variables shared by all sites in one place.
 */
if (file_exists('sites/all/metsis-global-settings.php')) {
  include 'sites/all/metsis-global-settings.php';
}
/**
 * Site-specific settings.
 */

/**
 * This file is loaded after all other multisite global settings have been loaded
 * Place the following at the end of the site specific settings.php
 * replaceing <mysite> with the name of the site.
 */

/**
 *
 * Custom <mysite> settings
 * if (file_exists('sites/<mysite>/metsis.custom.settings/metsis.settings.php')) {
 * include 'sites/<mysite>/metsis.custom.settings/metsis.settings.php';
 * }
 *
 */

/**
 * Set up the variable namespace for the METSIS modules
 */
global $metsis_conf;


/**
 * Create the Drupal node for the metsis qsearch form to appear.
 * E.g.
 * 1. create a Drupal "basic page" content type
 * 2. assign the URL alias metadata_search to the page
 * 3. set this variable's value to the 'metadata_search'
 */
$metsis_conf['metsis_qsearch_endpoint'] = 'metadata_search';

/**
 * @deprecated
 * site status: 'dev', 'test' or 'production'{
 * This should be set to 'production' for all sites
 * This variable will be removed in future releases
 */
$metsis_conf['site_status'] = 'production';

/**
 * Connection details of your metsis basket server here
 */
// $metsis_conf['metsis_basket_server'] = '<FQDN or IP address of basket server in single quotes.>';
$metsis_conf['metsis_basket_server'] = 'basket.metsis.met.no';
// $metsis_conf['metsis_basket_server_port'] = '<port number on the basket server in single quotes.>';
$metsis_conf['metsis_basket_server_port'] = '8080';
// $metsis_conf['metsis_basket_server_service'] = '<basket service path single quotes.>';
$metsis_conf['metsis_basket_server_service'] = '/basketService';

/**
 * Connection details of your METSIS OPeNDAP parser service
 */
//$metsis_conf['metsis_opendap_parser_ip'] = '<FQDN or IP address of OPeNDAP parser server in single quotes.>';
$metsis_conf['metsis_opendap_parser_ip'] = '***************';
//$metsis_conf['metsis_opendap_parser_port'] = '<port number on the OPeNDAP parser server in single quotes.>';
$metsis_conf['metsis_opendap_parser_port'] = '8080';
//$metsis_conf['metsis_opendap_parser_service'] = '<OPeNDAP parser service path single quotes.>';
$metsis_conf['metsis_opendap_parser_service'] = '/ometa/ometa';

/**
 * connection details of your Solr server
 */
//$metsis_conf['solr_server_ip'] = '<FQDN or IP address of Solr server in single quotes.>';
$metsis_conf['solr_server_ip'] = '***************';
//$metsis_conf['solr_server_port'] = '<port number on the Solr server in single quotes.>';
$metsis_conf['solr_server_port'] = '8080';

/**
 * Solr server cores to search for this site
 */
$metsis_conf['solr_core_parent'] = 'adc-l1';
$metsis_conf['solr_core_child'] = 'adc-l2';
$metsis_conf['solr_core_map_thumbnails'] = 'adc-thumbnail';
$metsis_conf['solr_core_config'] = 'adc-thumbnail';

/**
 * Solr metadata prefix
 */
$metsis_conf['metadata_prefix'] = 'mmd_';

/**
 * Solr data collections to search
 * These collections will be used to filter searches within your
 * site Solr cores.
 */
$metsis_conf['collections'] = 'ADC,NMAP,NBS';
// Determines whether the collections filter is visible in the search interface
$metsis_conf['collections_visible'] = TRUE;
// Determines whether the collections fieldset is expanded in the search interface
$metsis_conf['collections_initially_collapsed'] = TRUE;

/**
 * Polarisation mode
 * These setting are specific to https://satellittdata.no/
 * Leave them as they are for all other sites - they will not have any adverse
 * effect on your site.
 * Note. They will be removed in future releases
 */
$metsis_conf['instrument_polarisation_visible'] = FALSE;
$metsis_conf['instrument_polarisation_initially_collapsed'] = FALSE;
$metsis_conf['instrument_polarisations'] = 'HH,VV,HH+HV,VV+VH';
$metsis_conf['product_types_visible'] = FALSE;
$metsis_conf['product_types'] = 'L1C,L2A';
$metsis_conf['instrument_modes_visible'] = FALSE;
$metsis_conf['instrument_modes'] = 'IW,EW';

/**
 * Change these to match your live server details
 */
// The name of your site
$metsis_conf['drupal_site_name'] = "xyz.metsis.met.no";
// A brief description of your site
$metsis_conf['drupal_site_data_center_desc'] = "XYZ Data Management Service";

/**
 * WMS getcapabilities service URI
 * This is appended to your back office WMS server requests
 * e.g http://nbswms.met.no/thredds/wms_ql/NBS/S1B/2020/03/31/EW/S1B_EW_GRDM_1SDH_20200331T123901_20200331T124005_020936_027B60_E3DE.nc?SERVICE=WMS&REQUEST=GetCapabilities
 */
$metsis_conf['capdoc_postfix'] = "?SERVICE=WMS&REQUEST=GetCapabilities";

/**
 * Missing metadata strings
 * Set these to issue messages when metadata are missing or not applicable
 */
$metsis_conf['missing_metadata'] = "Missing metadata";
$metsis_conf['not_applicable_metadata'] = "NA";
$metsis_conf['missing_opendap'] = "OPeNDAP access unavailable";
$metsis_conf['missing_data_access_resource'] = "Missing data access resource information. Not added to basket.";

/**
 * Comment in/out elements of this array to change
 * what appears in the metadata tabulation which is displayed
 * at user request from the results tabulation page
 * */
$metsis_conf['metadata_visible'] = array(
  "mmd_title",
  "mmd_abstract",
  "mmd_personnel_name",
  "mmd_personnel_role",
  "mmd_personnel_organisation",
  "mmd_temporal_extent_start_date",
  "mmd_temporal_extent_end_date",
  "mmd_data_access_resource",
  "bbox",
  //"_version_",
  "mmd_metadata_identifier",
  "mmd_activity_type",
  "mmd_cloud_cover_value",
  "mmd_collection",
  //"mmd_data_access_description",
  //"mmd_data_access_type",
  "mmd_data_access_wms_layers_wms_layer",
  "mmd_data_center_contact_email",
  "mmd_data_center_contact_name",
  "mmd_data_center_contact_role",
  "mmd_data_center_data_center_name_long_name",
  "mmd_data_center_data_center_name_short_name",
  "mmd_data_center_data_center_url",
  "mmd_dataset_language",
  "mmd_dataset_production_status",
  "mmd_instrument_long_name",
  "mmd_instrument_short_name",
  "mmd_iso_topic_category",
  "mmd_keywords_keyword",
  "mmd_last_metadata_update",
  "mmd_metadata_status",
  "mmd_operational_status",
  "mmd_platform_long_name",
  "mmd_platform_short_name",
  "mmd_project_long_name",
  "mmd_project_short_name",
  "mmd_related_information_resource",
//  "mmd_related_information_type",
  "mmd_instrument_polarisation",
  "mmd_instrument_mode",
);

/**
 * Metadata sort order
 * See comment at https://phab.met.no/T2849
 * "Preferred order should be something like title, abstract,
 * PI (from personnel), start/end, bounding box,
 * access URLs and then the rest."
 * this array reflects metadata as they are in SOLR
 * a few elements (e.g. "bbox" and "id") are indexed in SOLR
 * without the METADATA_PREFIX
 * c.f. MMD specification document
 *
 * Change the order of elements in this array to change the order of
 * what appears in the metadata tabulation (buttons in search results table)
 *
 */
$metsis_conf['metadata_sort_order'] = array(
  "mmd_title",
  "mmd_abstract",
  "mmd_personnel_name",
  "mmd_personnel_role",
  "mmd_personnel_organisation",
  "mmd_temporal_extent_start_date",
  "mmd_temporal_extent_end_date",
  "mmd_data_access_resource",
  "bbox",
);


/**
 * Whether the basket is available.
 * setting this to false will remove all basket links such as
 * "add to basket", "go to basket" and checkboxes in the search results table
 */

$metsis_conf['basket_elements_visible'] = TRUE;

/**
* where the basket view is attached. This is
* the URI to your Drupal basket content
*/
$metsis_conf['basket_endpoint'] = "basket";
/**
 *whether a search form reset button is available
 */
$metsis_conf['form_reset_visible'] = TRUE;

/**
 * METSIS OpenLayers 3 WMS client paramters
 *
 */
/**
 * Lat/Lon values for three locations
 * defined for convenience.
 *
 */
$longyearbyen = array(
  'lat' => 78.22314167,
  'lon' => 15.64685556,
);
$tromsoe = array(
  'lat' => 69.659,
  'lon' => 18.984,
);
$metno = array(
  'lat' => 59.94266,
  'lon' => 10.72051,
);
/**
 * Center the map on the search interface on a given location
 */
$metsis_conf['search_map_center_lat'] = $longyearbyen['lat'];
$metsis_conf['search_map_center_lon'] = $longyearbyen['lon'];
/**
 * Set the zoom level for the map on the search interface
 */
$metsis_conf['search_map_init_zoom'] = 4.0;
/**
 * Center the map client on a given location when viewing data
 * in the OpenLayers 3 client
 */
$metsis_conf['wms_map_center_lat'] = $longyearbyen['lat'];
$metsis_conf['wms_map_center_lon'] = $longyearbyen['lon'];
/**
 * Set the zoom level for the map when viewing data
 * in the OpenLayers 3 client
 */
$metsis_conf['wms_map_init_zoom'] = 3.5;

/**
 * Determines whether to restrict the WMS layers in the OpenLayers
 * client to the list of layers indexed in Solr under
 * mmd_data_access_wms_layers_wms_layer
 * Setting this to 0 "zero" is safe and all layers
 * available in the GetCapabilities document will be passed to the
 * OpenLayers map client.
 */
$metsis_conf['wms_restrict_layers'] = 0;

/**
 * Deprecated variable wms_visible_layer_title. Leave it commented out.
 * It will be removed from the code and this document in future releases.
 *
 *$metsis_conf['wms_visible_layer_title'] = "True Color Vegetation Composite";
 */

/**
 * Exact string required by OL3 WMS client.
 */
$metsis_conf['wms_product_select'] = "false";
/**
 * Exact string required by OL3 WMS client.
 * Not setting this will default to 'north'
 */
//$metsis_conf['wms_which_base_layer'] = "north";
/**
 * Exact string required by OL3 WMS client.
 * Not setting this will default to 'true'
 */
 //$metsis_conf['wms_overlay_border'] = "true";

 /**
 * Data archive format for data downloads via the basket
 * "tgz" - tar gnu zip format.
 * This is supported on Linux, UNIX, Windows and Mac
 */
$metsis_conf['default_data_archive_format'] = "tgz";

/**
 * Whether to require user authentication
 * for basket or transform services.
 * 1 = user login required
 * 0 = user login not required
 */
$metsis_conf['authentication_required'] = 1;
/**
 * This message is displayed if a request requires authentication
 * and the requester is not logged in
 */
$metsis_conf['authentication_default_message'] = "The service you requested is only available to authenticated users. Please login or register.";

/**
 * Deprecated. Will be removed.
 * $metsis_conf['limit_empty_search'] = TRUE;
 */
/**
 * Maximum number of rows to fetch from Solr
 * This parameter will be removed in future releases once
 * the data in Solr has been restructured. The value
 * 3000 is a guesstimate, but much larger values will
 * affect the response time of the site and are not recommended.
 * Leave this unchanged for now.
 */
$metsis_conf['search_maximum_rows_to_fetch'] = 3000;

/**
 * The number of results to display per page on the
 * results tabulation pages.
 */
$metsis_conf['results_per_page'] = 17;

/**
 * Whether the tabulated metadata display is displayed
 * in an expanded div in the the results table.
 * FALSE => display table in a separate page.
 * Note that the user browser determines
 * whether the new page is displayed as a new tab or replaces
 * the current page.
 * TRUE => display table in a within the results table
 *
*/
$metsis_conf['show_metadata_inline'] = FALSE;

/**
 * Search only for "active" or "Active" datasets
 * Setting this parameter is optional. The default behavior
 * is to search for "active" datasets. (See MMD specification)
 * $metsis_conf['search_default_metadata_status'] = "active";
 */

/**
* Start/stop dates can be set for the search.
* The corresponding fields in the search interface will
* be prefilled accordingly.
* YYYY-MM-DD format must be used
* Single space between double quotes means blank start/stop date (recommended)
*/
$metsis_conf['default_start_date'] = " ";
$metsis_conf['default_end_date'] = " ";
/**
 * Deprecated variable. Will be removed in future releases.
 * It is recommended that you do not change this value.
 */
$metsis_conf['search_max_metadata_age'] = 540.00;


/**
 * Whether the topics and variables search form element is visible
*/
$metsis_conf['topics_and_variables_visible'] = TRUE;
/**
 * Whether the topics and variables search form fieldset is initially
 * in collapsed state
*/
$metsis_conf['topics_and_variables_initially_collapsed'] = TRUE;


/**
 * Whether the institutions search form element is visible
*/
$metsis_conf['institutions_visible'] = TRUE;
/**
 * Whether the institutions search form fieldset is initially
 * in collapsed state
*/
$metsis_conf['institutions_initially_collapsed'] = TRUE;
/**
 * Whether the institutions element is displayed in the search results table
*/
$metsis_conf['results_institutions_visible'] = TRUE;

/**
 * Whether the investigator search form element is visible
*/
$metsis_conf['investigator_visible'] = TRUE;
/**
 * Whether the investigator search form fieldset is initially
 * in collapsed state
*/
$metsis_conf['investigator_initially_collapsed'] = TRUE;


/**
 * Whether the abstract element is displayed in the search results table
*/
$metsis_conf['results_abstract_visible'] = TRUE;
/**
 * Whether the collection period element is displayed in the search results table
*/
$metsis_conf['results_collection_period_visible'] = TRUE;

/**
 * Whether the title element is displayed in the search results table
*/
$metsis_conf['title_visible'] = FALSE;

/**
 * Whether the project element is displayed in the search results table
*/
$metsis_conf['project_visible'] = FALSE;

/**
 * Whether the keywords element is displayed in the search results table
*/
$metsis_conf['results_keywords_visible'] = FALSE;


/**
 * Whether the collection element is displayed in the
 * level 1 search results table
*/
$metsis_conf['results_collection_visible'] = TRUE;

/**
 * Whether the platform search form element is visible
*/
$metsis_conf['platform_long_name_visible'] = FALSE;

/**
 * Whether the platform search form fieldset is initially
 * in collapsed state
*/
$metsis_conf['platform_long_name_initially_collapsed'] = TRUE;

/**
 * Whether the platform element is displayed in the search results table
*/
$metsis_conf['results_platform_long_name_visible'] = FALSE;

/**
 * Whether the investigator element is displayed in the search results table
*/
$metsis_conf['results_investigator_visible'] = TRUE;

/**
 * Whether the cloud cover element is displayed in the search results table
*/
$metsis_conf['results_cloud_cover_value_visible'] = FALSE;

/**
 * Whether the cloud cover search form element is visible
 * Note: this applies only to NBS Sentinel-2A
 *       and will be visible only if
 *       the platform element is visible in the
 *       search interface (see above)
*/
$metsis_conf['cloud_cover_value_visible'] = TRUE;

/**
 * Whether the cloud cover search form fieldset is initially
 * in collapsed state
 * Note: this applies only to NBS Sentinel-2A
 *       and will be visible only if
 *       the platform element is visible in the
 *       search interface (see above)
*/
$metsis_conf['cloud_cover_value_initially_collapsed'] = TRUE;

/**
 * The value options used for cloud cover in the search form
 * Note: this applies only to NBS Sentinel-2A
 *       and will be visible only if
 *       the platform element is visible in the
 *       search interface (see above)
 */
$metsis_conf['cloud_cover_value_search_options'] = array(
  "<10%",
  "<20%",
  "<30%",
  "<40%",
  "<50%",
  "<60%",
  "<70%",
  "<80%",
  "<90%",
  ">90%",
);
/**
 * Set the number of decimal places for cloud cover values
 * displayed in the level 1 results table.
 * Note: this applies only to NBS Sentinel-2A
 *       and will be visible only if
 *       the platform element is visible in the
 *       search interface (see above)
 */

$metsis_conf['results_number_decimal_display_format'] = 2;

/**
 * The variables:
 *      datasetName_visible
 *      collection_period_visible
 * are used for development purposes only.
 * Do not set any of them to FALSE for test or production sites
 *
 */
$metsis_conf['datasetName_visible'] = TRUE;
$metsis_conf['collection_period_visible'] = TRUE;

/**
 * Whether the collection period search form fieldset is initially
 * in collapsed state
*/
$metsis_conf['data_collection_period_initially_collapsed'] = TRUE;

/**
 * Whether the bounding box search form fieldset is initially
 * in collapsed state
*/
$metsis_conf['bounding_box_initially_collapsed'] = TRUE;

/**
 * Whether the full text search form fieldset is initially
 * in collapsed state
*/
$metsis_conf['full_text_search_initially_collapsed'] = TRUE;

/**
 * Determines the date and time the collection period element
 * displayed in the level 1 results tabulation.
 * Set this to  '' (two single quote with no space between)
 * for Solr index format.
 *
 * Examples of other formats:
 *
 *   'Y-m-d\TH:i:sP'    => e.g. 2005-08-15T15:52:01+00:00 (compatible with ISO-8601)
 *   'D, d M y H:i:s O' => e.g. Mon, 15 Aug 05 15:52:01 +0000
 *   'l, d-M-y H:i:s T' => e.g. Monday, 15-Aug-05 15:52:01 UTC
 *   'D, d M y H:i:s O' => e.g. Mon, 15 Aug 05 15:52:01 +0000
 *   'D, d M Y H:i:s O' => e.g. Mon, 15 Aug 2005 15:52:01 +0000
 *   'D, d M Y H:i:s O' => e.g. Mon, 15 Aug 2005 15:52:01 +0000
 *   'D, d M Y H:i:s O' => e.g. Mon, 15 Aug 2005 15:52:01 +0000
 *   'Y-m-d\TH:i:sP'    => e.g. 2005-08-15T15:52:01+00:00
 *   see http://php.net/manual/en/class.datetime.php for more details
 */
$metsis_conf['results_date_display_format'] = '';

/**
 * The full URL of the transformation sever (fimex) service
 * getCapabilities
 */
//$metsis_conf['transformation_server_getcapabilities'] = "<the full URL to your transformation server getCapabilities in double quotes>";
//e.g http://<FQDN or IP address of server>/cgi-bin/pywps.cgi?service=wps&version=1.0.0&request=getCapabilities";
$metsis_conf['transformation_server_getcapabilities'] = "http://***************/cgi-bin/pywps.cgi?service=wps&version=1.0.0&request=getCapabilities";

/**
 * Your Drupal transformation (fimex) service endpoint.
 */
$metsis_conf['transformation_endpoint'] = "metsis_fimex";

/**
 * Whether the transformation output format dropdown menu
 * is visible (fimex). The default output format is NetCDF.
 * However you may wish to offer other formats
 * (e.g. https://satellittdata.no/ offers NetCDF, NetCDF-4 and GeoTIFF)
 */
$metsis_conf['transformation_output_format_visible'] = TRUE;

/**
 * List of variables to EXCLUDE from those available variables on
 * the transformation form. By default all variable in the OPenDAP stream
 * are made available, however not all variable are suitable for the
 * transformation form (e.g. "swathList" for data from https://satellittdata.no/).
 */
//$metsis_conf['transformation_exclude_variables'] = 'projection,Granules_Level_1C_Tile_ID_metadata,Level_1C_DataStrip_ID_metadata,Level_1C_User_Product_metadata,swathList';

/**
 * The Web Map Service Drupal endpoint. You should
 * LEAVE THIS VARIABLE UNCHANGED. It is kept here for
 * development and testing convenience. The current value
 * is expected on production sites.
 * u
 */
$metsis_conf['wms_endpoint'] = "metsis/map/wms";

/**
 * Deprecated variable. Will be removed in future releases.
 * There is no need to change the value this variable.
 * Leave it for now!
 */
$metsis_conf['search_form_fields_empty_check'] = array(
  'chosen_topics_and_variables_a' => FALSE,
  'finished_after' => TRUE,
  'finished_before' => TRUE,
  'bbox_top_left_lon' => TRUE,
  'bbox_top_left_lat' => TRUE,
  'bbox_bottom_right_lon' => TRUE,
  'bbox_bottom_right_lat' => TRUE,
  'chosen_full_text_search' => TRUE,
  'chosen_investigator' => TRUE,
  'cloud_cover_value' => array(
    'chosen_cloud_cover_value' => TRUE,
  )
);

/**
 * This variable creates a namespace for general messages to user.
 * Currently only the 'under_construction' message is used in the source code.
 * It may be removed or changed in future releases. It is recommend that you
 * do not modify this variable.
 */
$metsis_conf['message'] = [];
/**
 * Determines whether the message is visible. It is recommended that
 * you leave this variable value as FALSE
 */
$metsis_conf['message']['visible'] = FALSE;
/**
 * The message to be displayed.
 */
$metsis_conf['message']['under_construction'] = "This site is under construction. Communication with backends may be slow.";

/**
 * If set, landing_page_button_var can be one of, "title" or "metadata_identifier"
 * "title" and "metadata_identifier" will be retrieved from Solr
 * default is title and commenting out this var will use title
 */
$metsis_conf['landing_page_button_var'] = 'metadata_identifier';

/**
 * Sets the text displayed on the data download link/button
 */
$metsis_conf['dar_http_button_text'] = 'Download data';

/**
 * Set the text displayed on the original (original format)
 * download link/button.
 * E.g. https://colhub.met.no/odata/v1/Products('24c27879-d7ad-4873-a97b-d8aadcb90bd3')/$value
 * Note that this link may require the user to authenticate
 */
//$metsis_conf['dar_odata_button_text'] = 'Download .SAFE product';

/**
 * Sets the text displayed on the data OPeNDAP link/button
 */
$metsis_conf['dar_opendap_button_text'] = 'OPeNDAP';

/**
 * Sets the text displayed on the OGC WMS link/button
 */
$metsis_conf['dar_ogc_wms_button_text'] = 'OGC WMS';

/**
 * Sets the text displayed on the metadata link/button
 */
$metsis_conf['solr_metadata_button_text'] = 'View metadata';

/**
 * The Zoo WPS time series service server IP or FQDN
 */
$metsis_conf['ts_server'] = "adcwps.met.no";

/**
 * The time series Druapl endpoint.
 * It is recommended that you create a Drupal basic page and
 * limit the visibility of the time series form to that page
 */
$metsis_conf['ts_endpoint'] = "ts";

/**
 * Sets the text displayed on the time series visualization link/button
 */
$metsis_conf['ts_visualization_button_text'] = "Visualize";

/**
 * Default maximum number of points to plot.
 * If the variable contains more than ts_plot_npoints of data points
 * it will be resampled to ts_plot_npoints.
 * The time series plot form allows the user to change this value.
 */
$metsis_conf['ts_plot_npoints'] = 150;

/**
 * Variables that should not appear in time series plotting options form.
 */
$metsis_conf['ts_exclude_variables'] = array('latitude', 'longitude', 'height', 'surface_altitude');


/**
 * The Zoo WPS ASCII download service server IP or FQDN
 */
$metsis_conf['csv_server'] = "adcwps.met.no";

/**
 * The CSV Druapl endpoint.
 * It is recommended that you create a Drupal basic page and
 * limit the visibility of the ASCII download form to that page
 */
$metsis_conf['csv_endpoint'] = "csv";

/**
 * Sets the text displayed on the ASCII download link/button
 */
$metsis_conf['csv_button_text'] = "ASCII";

/**
 * Default maximum number of points to download.
 * If the variable contains more than csv_npoints of data points
 * it will be resampled to csv_npoints.
 * The recommended default value is 1 (one).
 * This is not a user configurable value.
 */
$metsis_conf['csv_npoints'] = 1;

/**
 * Variables that should not appear in CVS ASCII download options form.
 */
$metsis_conf['csv_exclude_variables'] = array('latitude', 'longitude', 'height', 'surface_altitude');

/**
 * The level 2 data Drupal service endpoint.
 * It is recommended that you create a Drupal basic page
 * for this endpoint and limit the block display to that page
 */
$metsis_conf['elements_endpoint'] = "child";

/**
 * Sets the text displayed on the level 2 data link/button
 */
$metsis_conf['elements_button_text'] = "Child data";

/**
 * Do not change this variable.
 */
$metsis_conf['required_child_metadata'] = 'mmd_personnel_organisation,'
  . 'mmd_metadata_identifier,'
  . 'mmd_title,'
  . 'mmd_temporal_extent_start_date,'
  . 'mmd_temporal_extent_end_date,'
  . 'mmd_data_access_resource,'
  . 'mmd_related_information_resource,'
  . 'mmd_personnel_name';


/**
 * Whether the navigation elements (buttons/links) on the
 * level 1 results tabulation page remain at the bottom
 * of the visible window when scrolling.
 *
 * This is an experimental feature which may be removed in future
 * releases.
 *
 * It is recommended that you set it to FALSE.
 */
$metsis_conf['adc_floating_buttons'] = FALSE;


/**
 * Sharing searches can be done in one of two mutually exclusive ways:
 * 1. creating an email with the unique search URL inserted in
 *    the body of the message
 * 2. displaying the URL on screen for copying and pasting.
 */
/**
 * 1. email method
 * Determines whether the unique URL for the current search
 * should be shared by email.
 *
 * Setting this variable to TRUE will result in the browser
 * initiating an email in a mail client with the sharable search
 * URL as the content.
 */
$metsis_conf['share_results_email_button_visible'] = FALSE;

/**
 * Sets the text displayed on the email sharable search link/button
 */
$metsis_conf['share_results_email_button_text'] = "Share results";

/**
 * 2. cut and paste method
 * Determines whether the unique URL for the current search
 * should be displayed on screen for copying and pasting.
 */
$metsis_conf['share_results_copy_button_visible'] = TRUE;


/**
 * Sets the text displayed on the cut and paste sharable search link/button
 */
$metsis_conf['share_results_copy_button_text'] = "Search ID";

/**
 * Labels, hints and placeholders
 * The fieldsets and input elements in the search form can be configured
 * to display custom labels, examples of entries, and palace holders
 * to show expected input formats
 */
/**
 * The data collection period input elements
 */
$metsis_conf['label_temporal_extent'] = 'Data Collection Period';
$metsis_conf['hint_temporal_extent_start_date'] = 'Start Date';
$metsis_conf['placeholder_temporal_extent_start_date'] = 'yyyy-mm-dd';
$metsis_conf['hint_temporal_extent_end_date'] = 'End Date';
$metsis_conf['placeholder_temporal_extent_end_date'] = 'yyyy-mm-dd';

/**
 * The geographical extent (text input fields) input elements
 */
$metsis_conf['label_bounding_box'] = 'Bounding Box';
$metsis_conf['hint_top_left_longitude'] = 'top left longitude';
$metsis_conf['placeholder_top_left_longitude'] = '';
$metsis_conf['hint_top_left_latitude'] = 'top left latitude';
$metsis_conf['placeholder_top_left_latitude'] = '';
$metsis_conf['hint_bottom_right_longitude'] = 'bottom right longitude';
$metsis_conf['placeholder_bottom_right_longitude'] = '';
$metsis_conf['hint_bottom_right_latitude'] = 'bottom right latitude';
$metsis_conf['placeholder_bottom_right_latitude'] = '';

/**
 * The full text (text input field) input elements
 */
$metsis_conf['label_full_text'] = 'label_full_text';
$metsis_conf['hint_full_text'] = 'Combine search keywords: e.g "radiosonde AND humidity"';
$metsis_conf['placeholder_full_text'] = '';

/**
 * The geographical extent (map selection) elements
 */
$metsis_conf['label_geographic_extent'] = 'Geographical Extent';

/**
 * The institution selection element.
 */
$metsis_conf['label_institutions'] = 'Institutions';
$metsis_conf['label_platform_long_name'] = 'Platforms';

/**
 * The investigator (text input field) input elements
 */
$metsis_conf['label_investigator'] = 'Investigator';
$metsis_conf['hint_investigator'] = 'The name of the Principal Investigator';
$metsis_conf['placeholder_investigator'] = '';

/**
 * The collections selection element.
 */
$metsis_conf['label_collections'] = 'Collections';


/**
 * The topics and variables (text input field) input elements
 */
$metsis_conf['label_topics_and_variables'] = 'Topics and Variables';
$metsis_conf['hint_topics_and_variables'] = 'Start typing: available keywords will show';
$metsis_conf['placeholder_topics_and_variables'] = '';

/*
 * Determines whether thumbnails in the search results tabulation
 * are displayed in a separate column.
 * Commenting out this variable will default to thumbnails
 * appearing in the "Dataset name" column
 */
//$metsis_conf['results_thumb_column_header'] = 'Thumbnails';



/**
 * The remaining variables are used mainly for development and testing.
 * You can safely leave them unchanged.
 */
/**
 * Variable used primarily for development and testing.
 * An example of how to display site information.
 *
 */
$dev_message = 'Site: <span style="color:red; font-size: 200%;"> mysite </span>';
$dev_message .= ' Solr core: <span style="color:red; font-size: 200%;">' . $metsis_conf["solr_core_parent"] . ' </span>';
$dev_message .= ' Updated: <span style="color:red; font-size: 200%;"> mydate </span>';
//drupal_set_message($dev_message, 'warning');


/**
 * DEBUG{
 * This is only used by developers of the METSIS modules
 * Live sites should set this value to 0
 * It is IMPORTANT to set this variable value to 0 on
 * production sites to avoid storing large amounts of
 * log data in the database
 */
// 0 = debugging off
// 1 = debugging on
$metsis_conf['debug'] = 0;
/**
 * DEBUG}
 */
/**
 * warnings
 */
$metsis_conf['warning']['transformation']="Due to internal communication issues,
the transformation service is sometimes not working. Please try your request two
times. We are looking into solving the issue and apologize for any inconvenience
this may cause.";
