<?php

/*
 * ********************************************************************
 *                                                                   *
 * DO NOT EDIT this file unless you are comfortable with             *
 * the inner workings of Drupal and the METSIS modules.              *
 * Mistakes in this file WILL BREAK YOUR SITE.                       *
 *                                                                   *
 * *******************************************************************
 */
# METSIS global/shared settings
if (file_exists('sites/all/metsis-global-settings.php')) {
  include 'sites/all/metsis-global-settings.php';
}

/**
 * @file
 * site-specific settings for metsis multi-sites.
 * The general rule is create variable in a such way that 
 * if they are undefined the site will still work.
 * The alternative is to ALWAYS test for definition before use.
 * 
 */
/**
 * This file is loaded after all other multisite global settings have been loaded
 * Place the follwing at the end of the site specific settings.php (after the globa/shared settings if block),
 * replaceing <mutisite site> with the name of the site.
 */
/**
 * 
  # custom <multisite site> settings
  if (file_exists('sites/<multisite site>.metsis.met.no/metsis.custom.settings/metsis.settings.php')) {
  include 'sites/<multisite site>.metsis.met.no/metsis.custom.settings/metsis.settings.php';
  }
 * 
 */
global $metsis_conf;
/**
 * a few of these are candidates for global settings files, but are kept here to ensure maximum flexibility.
 */
/*
 * metsis basket server on ARES
 */
//metsis_basket_server has an entry in the global DNS, but is (and should be) accessible
//only to the metsis machines on ARES
//$metsis_conf['metsis_basket_server_ip']='157.249.176.100';

$metsis_conf['metsis_basket_server'] = 'basket.metsis.met.no';
$metsis_conf['metsis_basket_server_port'] = '8080';
$metsis_conf['metsis_basket_server_service'] = '/basketService';


//$metsis_conf['solr_server_ip']   = '10.99.3.36';
//on Ares
$metsis_conf['solr_server_ip'] = '157.249.176.182';
$metsis_conf['solr_server_port'] = '8080';

/**
 * SOLR server core details
 */
$metsis_conf['solr_core_parent'] = 'normap-l1';
$metsis_conf['solr_core_child'] = 'normap-l2';
$metsis_conf['solr_core_map_thumbnails'] = 'normap-thumbnail';

/**
 * local dev vm server
 * change these to match your live server details
 */
$metsis_conf['drupal_server'] = 'staging.dmsite';
$metsis_conf['drupal_server_protocol'] = "https";
$metsis_conf['drupal_server_port'] = '80';
$metsis_conf['drupal_server_ssl_port'] = '443';
$metsis_conf['drupal_site_name'] = "staging.dmsite";
$metsis_conf['drupal_site_data_center_desc'] = "SIOS Data Management Service";


/**
 * background maps from public servers
 */
$metsis_conf['metno_public_wms'] = "public-wms.met.no";
$metsis_conf['mapthumb_base_image'] = "http://"
  . $metsis_conf['metno_public_wms'] .
  "/backgroundmaps/northpole.map"
  . "?SERVICE=WMS"
  . "&REQUEST=GetMap"
  . "&VERSION=1.1.1"
  . "&FORMAT=image%2Fpng&SRS=EPSG:32661"
  . "&BBOX=-3000000,-3000000,7000000,7000000"
  . "&WIDTH=64"
  . "&HEIGHT=64"
  . "&EXCEPTIONS=application%2Fvnd.ogc.se_inimage"
  . "&TRANSPARENT=true"
  . "&LAYERS=borders"
  . "&STYLES=";


/**
 * solr metadata prefix
 * All metadata with the exception of id are prefixed with "mmd_" in SOLR
 * "mmd_" is peculiar to METNO and should therefore be parametrized here
 * and provided as a configuration parameter in the configuration interface.
 */
$metsis_conf['metadata_prefix'] = 'mmd_';

/**
 * capdoc options
 */
$metsis_conf['capdoc_postfix'] = "?SERVICE=WMS&version=1.3.0&request=GetCapabilities";

/**
 * missing metadata strings
 */
$metsis_conf['missing_metadata'] = "Missing metadata";
$metsis_conf['missing_opendap'] = "OPeNDAP access unavailable";
/**
 * HTTP(S)
 */
//$conf['https'] = FALSE;
/*
 * metadata_sort_order{
 * See comment at https://phab.met.no/T2849
 * "Preferred order should bes something like title, abstract, PI (from personnel), start/end, boundingbox, 
 * access URLs and then the rest."
 * this array reflects metadata as they are in SOLR 
 * a few elements (e.g. "bbox" and "id") are indexed in SOLR without the prefix METADATA_PREFIX
 * the reason for this mixed convention is not clear as of this writing (2016-10-18)
 * c.f. MMD specification document
 * 
 */
$metsis_conf['metadata_sort_order'] = array(
  "mmd_title",
  "mmd_abstract",
  "mmd_personnel_name",
  "mmd_personnel_role",
  "mmd_personnel_organisation",
  "mmd_temporal_extent_start_date",
  "mmd_temporal_extent_end_date",
  "mmd_geographic_extent_rectangle_north",
  "mmd_geographic_extent_rectangle_south",
  "mmd_geographic_extent_rectangle_east",
  "mmd_geographic_extent_rectangle_west",
  "mmd_data_access_resource",
  "bbox",
);
/*
 * metadata_sort_order}
 */
/*
 * metsis web interface elements{
 */
//These will be moved to admin interface as options
$metsis_conf['basket_elements_visible'] = TRUE;
$metsis_conf['form_reset_visible'] = TRUE;
/*
 * metsis web interface elements}
 */
/*
 * metsis OL3 WMS{
 */
$longyearbyen = array(
  'lat' => 78.22314167,
  'lon' => 15.64685556);
$metsis_conf['search_map_center_lat'] = $longyearbyen['lat'];
$metsis_conf['search_map_center_lon'] = $longyearbyen['lon'];
$metsis_conf['search_map_init_zoom'] = 4.0;
$metsis_conf['wms_map_center_lat'] = $longyearbyen['lat'];
$metsis_conf['wms_map_center_lon'] = $longyearbyen['lon'];
$metsis_conf['wms_map_init_zoom'] = 5;
$metsis_conf['wms_visible_layer_title'] = "";
//$metsis_conf['wms_visible_layer_title'] = "averaged sea ice edge";
/*
 * metsis OL3 WMS}
 */
/*
 * drupal service endpoints{ 
 */
$metsis_conf['basket_endpoint'] = "/basket";
/*
 * drupal service endpoints}
 */

/*
 * default data archive format{
 * "tgz" - tar gnu zip format. This is supported on Linux, UNIX, Windows and Mac
 */
$metsis_conf['default_data_archive_format'] = "tgz";
/*
 * default data archive format}
 */
/*
 * {}
 */
