<?php
use Drupal\Core\Render\Markup;

require_once drupal_get_path('module', 'metsis_elements') . '/includes/metsis_elements.constants.inc';
require_once drupal_get_path('module', 'metsis_elements') . '/includes/metsis_elements.utils.inc';
require_once drupal_get_path('module', 'metsis_elements') . '/includes/metsis_elements_forms.inc';
require_once drupal_get_path('module', 'metsis_qsearch') . '/metsis_qsearch.constants.inc';

/**
 * removed in Drupal 8
 *
 */
 /*
function metsis_elements_init() {

}
*/

function metsis_elements_help($path, $arg) {
  switch ($path) {
    case 'admin/help#metsis_elements': $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The METSIS ELEMENTS module provides a
                block containing a tabular form for level 2 datasets.
                Enable this module to provide the "metsis_elements" block. Then go to the
                <a href="@metsis_elements">blocks admin page</a>', array('@metsis_elements' => '/metsis_elements#overlay=admin/structure/block')) . ' to activate and configure METSIS ELEMENTS.</p>';
      return Markup::create($output);
    case 'admin/content/metsis_elements': return Markup::create('<p>' . t('METSIS ELEMENTS.') . '</p>');
  }
}
/*
function metsis_elements_block_info() {
  $blocks['metsis_elements_config_form'] = array('info' => t('metsis_elements config form'), 'cache' => DRUPAL_NO_CACHE,);
  return $blocks;
}

function metsis_elements_block_view($delta = '') {
  switch ($delta) {
    case 'metsis_elements_config_form': if (\Drupal::currentUser()->hasPermission('access content')) {
        $block['content'] = \Drupal::formBuilder()->getForm('elements_tabular_form');
        return $block;
      } break;
  }
}
*/
function metsis_elements_theme() {
  return [
    'metsis_elements_form' => [
      'template' => 'metsis-elements-form',
      'render element' => 'form',
      //'base hook' => 'form'
    ],
  ];
}
