<?php

/**
 * @file
 * Module for adding datasets to basket.
 */

/**
 * Display help from this module.
 */
function metsis_basket_help($path, $arg) {
  switch ($path) {
    case 'admin/help#metsis_basket':
      $output = '<h3>About</h3>';
      $output .= '<p>Module implementing basket functionality. </p>';
      return $output;

    case 'admin/content/metsis_basket':
      return '<p>The basket. </p>';
  }
}

/**
 * Implements hook_theme().
 */
function metsis_basket_theme($existing, $type, $theme, $path) {
  return [
    'metsis_basket-template' => [
  // To render a simple container element.
      'render element' => 'container',
  // My template file name.
      'template' => 'metsis_basket',
      'variables' => [],
    ],
  ];
}

/**
 * Map old settings permission to new permissions.
 */
function metsis_basket_update_8007() {
  $roles = \Drupal::entityTypeManager()->getStorage('user_role')->loadMultiple();
  foreach ($roles as $role) {
    /** @var \Drupal\user\RoleInterface $role */
    if ($role->hasPermission('execute metsis_basket_delete_action metsis_basket_item')) {
      $role->revokePermission('execute metsis_basket_delete_action metsis_basket_item');
      $role->grantPermission('access metsis basket');
      $role->save();
    }
  }
}
