map_base_layer_wms_north: 'https://public-wms.met.no/backgroundmaps/northpole.map'
map_base_layer_wms_south: 'https://public-wms.met.no/backgroundmaps/southpole.map'
map_init_proj: 'EPSG:4326'
map_projections:
  'EPSG:4326': 'EPSG:4326'
  'EPSG:32661': 'UPS North'
  'EPSG:32761': 'UPS South'
map_additional_layers: '1'
map_zoom: '3.5'
map_locations:
  longyearbyen:
    lat: 78.22314167
    lon: 15.64685556
  tromsoe:
    lat: 69.659
    lon: 18.984
  metno:
    lat: 59.94266
    lon: 10.72051
map_selected_location: longyearbyen
map_bbox_filter: Within
map_search_text: 'Click on the map to draw a selection box. Boxes in UPS are transfomed into 4-edge polygons'
map_layers:
  - europaveg
  - riksveg
  - fylkesveg
map_pins: '1'
dar_http: 'Download data'
dar_odata: 'Download SAFE product'
dar_opendap: OPeNDAP
dar_ogc_wms: 'OGC WMS'
lp_button_var: title
ts_server_type: pywps
ts_button_text: 'Viusalize timeseries'
csv_button_text: 'Download dataset as ASCII'
map_additional_layers_b: true
map_pins_b: true
selected_collections:
  ADC: ADC
  NSDN: NSDN
  GCW: GCW
  SIOS: SIOS
  NMAP: NMAP
  YOPP: YOPP
  APPL: APPL
  NMDC: NMDC
pywps_service: 'https://ncapi.adc-ncplot.met.no/ncplot/plot'
