<?php

function metsis_cache_schema() {
  $schema = array();
  $schema['metsis_cache'] = array('description' => 'The base table for the information we want available to Views.', 'fields' => array('id' => array('description' => 'Primary key of the record.', 'type' => 'serial', 'unsigned' => TRUE, 'not null' => TRUE,), 'name' => array('description' => 'A simple text field.', 'type' => 'varchar', 'length' => 255, 'not null' => FALSE,), 'deadline' => array('description' => 'A date stored as an integer timestamp.', 'type' => 'int', 'length' => 11, 'not null' => FALSE,), 'node_id' => array('description' => 'A Drupal node related to this record.', 'type' => 'int', 'length' => 11, 'not null' => FALSE,),), 'primary key' => array('id'),);
  return $schema;
}
